[package]
name = "nix-search"
version = "0.1.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
